baseURL = "/"
title = "Martin Baumgärtner"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

canonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
relativeURLs = true
unsafeHTML = false

[pagination]
pagerSize = 10
path = 'page'

[services.rss]
limit = 10

[permalinks]
posts = "/posts/:year/:month/:title/"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

description = "Data Scientist, Ph.D. in Economics. Currently @ Rewe. Specializing in econometrics, monetary policy, and time series analysis. Research in VAR models and natural language processing."
keywords = "Economics, Monetary policy, Time series, Econometrics, VAR models, Data science, Research, NLP, Neural networks"
defaultTheme = "dark"

homeSubtitle = "Data Scientist, Ph.D. in Economics. Currently @ Rewe."

disableReadOtherPosts = false
enableThemeToggle = false
enableSharingButtons = true
enableReadingTime = true
enableGlobalLanguageMenu = false

[params.author]
name = "Martin Baumgärtner"
email = "martin.baumgaertner1@gmail.com"

[params.og]
type = "website"
image = "/img/og-image.png"

[params.footer]
trademark = 2026
rss = true
copyright = true
author = true
topText = []
bottomText = []

[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[params.logo]
logoMark = ">"
logoText = "Martin Baumgärtner"
logoHomeLink = "/"

# Social links
[[params.social]]
name = "email"
url = "mailto:martin.baumgaertner1@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/martinbaumgaertner"

[[params.social]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=MI2L_pIAAAAJ&hl=de/"

[languages.en]
weight = 1

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publication/"
weight = 30

[[menu.main]]
identifier = "code"
name = "Code"
url = "/code/"
weight = 40
